import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Navbar } from "@/components/Navbar"
import { Footer } from "@/components/Footer"
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Viktor Ralchenko Portfolio",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body className={`${inter.className} min-h-dvh md:h-dvh flex flex-col md:overflow-hidden`}>
                <Navbar />
                {children}
                <Footer />
                <Toaster theme="dark" position="bottom-center" />
            </body>
        </html>
    )
}