import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"
import { Navbar } from "@/components/Navbar"
import { Footer } from "@/components/Footer"
import { Toaster } from "sonner"
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Viktor Ralchenko Portfolio",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {
    const { locale } = await params;

    if (!routing.locales.includes(locale as any)) {
        notFound();
    }

    const messages = await getMessages();

    return (
        <html lang={locale} className="dark">
            <body className={`${inter.className} min-h-dvh md:h-dvh flex flex-col md:overflow-hidden`}>
                <NextIntlClientProvider messages={messages}>
                    <Navbar />
                    {children}
                    <Footer />
                    <Toaster theme="dark" position="bottom-center" />
                </NextIntlClientProvider>
            </body>
        </html>
    )
}